<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Grasshopper" VersionOverride="8.0.23304.9001" PrivateAssets="all" />
    <PackageReference Include="RhinoCommon" VersionOverride="8.0.23304.9001" PrivateAssets="all" />
    <ProjectReference Include="..\..\..\src\SimpleDragon\GonieGonie.SimpleDragon.Grasshopper.Types\GonieGonie.SimpleDragon.Grasshopper.Types.csproj" />
    <ProjectReference Include="..\..\..\src\SimpleDragon\GonieGonie.SimpleDragon.GH\GonieGonie.SimpleDragon.GH.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
