using System.Collections.ObjectModel;
using GonieGonie.BuildingEnergy.Contracts;
using GonieGonie.InvisibleDragon.Rhino;
using Rhino.Geometry;
using DragonSurface = GonieGonie.InvisibleDragon.Shape.Surface;
using SimpleSurface = GonieGonie.SimpleDragon.Surface;

namespace GonieGonie.SimpleDragon.Rhino;

/// <summary>
/// One caller-disposable Rhino face representing the exact polygon generated by
/// the SimpleDragon-to-InvisibleDragon conversion.
/// </summary>
public sealed class RhinoConvertedSurfacePreview : IDisposable
{
    internal RhinoConvertedSurfacePreview(
        EntityId convertedSurfaceId,
        EntityId? sourceSurfaceId,
        EntityId? sourceZoneId,
        EntityId? convertedZoneId,
        bool isSynthesizedCounterpart,
        Brep geometry,
        Brep explodedGeometry,
        Point3d labelPoint,
        Point3d explodedLabelPoint,
        double? sourceGrossArea,
        double? sourceOpeningArea,
        double convertedGrossArea,
        double convertedOpeningArea,
        double convertedNetArea,
        double rhinoNetArea,
        string geometryFingerprint,
        GeometryProvenance? sourceGeometry)
    {
        ConvertedSurfaceId = convertedSurfaceId;
        SourceSurfaceId = sourceSurfaceId;
        SourceZoneId = sourceZoneId;
        ConvertedZoneId = convertedZoneId;
        IsSynthesizedCounterpart = isSynthesizedCounterpart;
        Geometry = geometry;
        ExplodedGeometry = explodedGeometry;
        LabelPoint = labelPoint;
        ExplodedLabelPoint = explodedLabelPoint;
        SourceGrossArea = sourceGrossArea;
        SourceOpeningArea = sourceOpeningArea;
        ConvertedGrossArea = convertedGrossArea;
        ConvertedOpeningArea = convertedOpeningArea;
        ConvertedNetArea = convertedNetArea;
        RhinoNetArea = rhinoNetArea;
        GeometryFingerprint = geometryFingerprint;
        SourceGeometry = sourceGeometry;
    }

    public EntityId ConvertedSurfaceId { get; }

    public EntityId? SourceSurfaceId { get; }

    public EntityId? SourceZoneId { get; }

    public EntityId? ConvertedZoneId { get; }

    public bool IsSynthesizedCounterpart { get; }

    public Brep Geometry { get; }

    public Brep ExplodedGeometry { get; }

    public Point3d LabelPoint { get; }

    public Point3d ExplodedLabelPoint { get; }

    public string Label => ConvertedSurfaceId.Value;

    public double? SourceGrossArea { get; }

    public double? SourceOpeningArea { get; }

    public double ConvertedGrossArea { get; }

    public double ConvertedOpeningArea { get; }

    public double ConvertedNetArea { get; }

    public double RhinoNetArea { get; }

    public string GeometryFingerprint { get; }

    public GeometryProvenance? SourceGeometry { get; }

    public string? SourceGeometryFingerprint => SourceGeometry?.GeometryFingerprint;

    public double? GrossAreaDifference => SourceGrossArea.HasValue
        ? ConvertedGrossArea - SourceGrossArea.Value
        : null;

    public double? OpeningAreaDifference => SourceOpeningArea.HasValue
        ? ConvertedOpeningArea - SourceOpeningArea.Value
        : null;

    public void Dispose()
    {
        Geometry.Dispose();
        ExplodedGeometry.Dispose();
    }
}

/// <summary>
/// Owns the generated Breps in a converted-model preview.
/// </summary>
public sealed class RhinoConversionPreview : IDisposable
{
    private bool disposed;

    internal RhinoConversionPreview(
        IEnumerable<RhinoConvertedSurfacePreview> surfaces,
        IEnumerable<Diagnostic> diagnostics)
    {
        Surfaces = new ReadOnlyCollection<RhinoConvertedSurfacePreview>(surfaces.ToArray());
        Diagnostics = new ReadOnlyCollection<Diagnostic>(diagnostics.ToArray());
    }

    public IReadOnlyList<RhinoConvertedSurfacePreview> Surfaces { get; }

    public IReadOnlyList<Diagnostic> Diagnostics { get; }

    public bool Success => Surfaces.Count > 0 && Diagnostics.All(item => !item.IsFailure);

    public void Dispose()
    {
        if (disposed)
        {
            return;
        }

        foreach (RhinoConvertedSurfacePreview surface in Surfaces)
        {
            surface.Dispose();
        }

        disposed = true;
    }
}

public static class RhinoConversionPreviewBuilder
{
    public static RhinoConversionPreview Create(
        GreenRetrofitModel source,
        GreenRetrofitConversionResult conversion,
        RhinoGeometryContext context,
        IEnumerable<RhinoDomainGeometryMapEntry>? sourceGeometryMap = null,
        double explodeDistanceMetres = 0.25d)
    {
        RequireNotNull(source, nameof(source));
        RequireNotNull(conversion, nameof(conversion));
        RequireNotNull(context, nameof(context));
        if (double.IsNaN(explodeDistanceMetres)
            || double.IsInfinity(explodeDistanceMetres)
            || explodeDistanceMetres < 0d)
        {
            throw new ArgumentOutOfRangeException(
                nameof(explodeDistanceMetres),
                explodeDistanceMetres,
                "The exploded-preview distance must be finite and non-negative.");
        }

        var diagnostics = conversion.Diagnostics.ToList();
        var previews = new List<RhinoConvertedSurfacePreview>();
        if (conversion.EnergyModel is null)
        {
            diagnostics.Add(new Diagnostic(
                "SD.RHINO.PREVIEW_MODEL_UNAVAILABLE",
                DiagnosticSeverity.Error,
                "The SimpleDragon conversion did not produce an InvisibleDragon model.",
                suggestedAction: "Correct the conversion diagnostics before creating a preview."));
            return new RhinoConversionPreview(previews, diagnostics);
        }

        Dictionary<string, SimpleSurface> sourceById = source.Zones
            .SelectMany(zone => zone.Surfaces)
            .GroupBy(surface => surface.Id.Value, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.First(), StringComparer.Ordinal);
        var conversionByOutputId = new Dictionary<string, GreenRetrofitSurfaceConversion>(StringComparer.Ordinal);
        foreach (GreenRetrofitSurfaceConversion surfaceConversion in conversion.SurfaceConversions)
        {
            if (!TryAdd(
                    conversionByOutputId,
                    surfaceConversion.ConvertedSurfaceId.Value,
                    surfaceConversion))
            {
                diagnostics.Add(new Diagnostic(
                    "SD.RHINO.PREVIEW_DUPLICATE_CONVERSION_MAPPING",
                    DiagnosticSeverity.Error,
                    "More than one SimpleDragon source mapping targets the same InvisibleDragon surface.",
                    surfaceConversion.ConvertedSurfaceId,
                    suggestedAction: "Regenerate the conversion result and inspect reciprocal adjacency diagnostics."));
            }
        }

        var provenanceById = new Dictionary<string, GeometryProvenance>(StringComparer.Ordinal);
        foreach (RhinoDomainGeometryMapEntry entry in sourceGeometryMap
                     ?? Array.Empty<RhinoDomainGeometryMapEntry>())
        {
            if (entry.Kind != RhinoMappedGeometryKind.Surface)
            {
                continue;
            }

            if (!TryAdd(provenanceById, entry.EntityId.Value, entry.Provenance))
            {
                diagnostics.Add(new Diagnostic(
                    "SD.RHINO.PREVIEW_DUPLICATE_SOURCE_PROVENANCE",
                    DiagnosticSeverity.Warning,
                    "More than one Rhino provenance entry exists for a SimpleDragon surface; the first was used.",
                    entry.EntityId,
                    entry.Provenance,
                    "Keep one surface mapping entry per SimpleDragon entity."));
            }
        }

        int convertedIndex = 0;
        foreach (DragonSurface converted in conversion.EnergyModel.Surfaces)
        {
            conversionByOutputId.TryGetValue(
                converted.Id.Value,
                out GreenRetrofitSurfaceConversion? surfaceConversion);
            string sourceIdText = surfaceConversion?.SourceSurfaceId.Value ?? converted.Id.Value;
            if (!sourceById.TryGetValue(sourceIdText, out SimpleSurface? sourceSurface))
            {
                if (!sourceById.TryGetValue(converted.Id.Value, out sourceSurface)
                    && surfaceConversion is null
                    && converted.Id.Value.StartsWith("$CLONE_OF$:", StringComparison.Ordinal))
                {
                    sourceIdText = converted.Id.Value.Remove(0, "$CLONE_OF$:".Length);
                    sourceById.TryGetValue(sourceIdText, out sourceSurface);
                }
            }

            provenanceById.TryGetValue(sourceSurface?.Id.Value ?? string.Empty, out GeometryProvenance? sourceGeometry);
            Brep? brep = null;
            Brep? exploded = null;
            try
            {
                brep = RhinoSurfaceAdapter.ToBrep(converted, context);
                double rhinoNetArea = brep.GetArea()
                    * context.SourceUnitsToMetres
                    * context.SourceUnitsToMetres;
                double tolerance = Math.Max(
                    GonieGonie.InvisibleDragon.Shape.GeometryTolerance.Area,
                    converted.NetArea * 1e-8d);
                if (Math.Abs(rhinoNetArea - converted.NetArea) > tolerance)
                {
                    diagnostics.Add(new Diagnostic(
                        "SD.RHINO.PREVIEW_AREA_MISMATCH",
                        DiagnosticSeverity.Error,
                        "The Rhino preview area differs from the converted InvisibleDragon surface.",
                        converted.Id,
                        suggestedAction: "Inspect the conversion polygon and Rhino document tolerance."));
                }

                double convertedOpeningArea = converted.Openings.Sum(opening => opening.Polygon.Area);
                if (sourceSurface is null)
                {
                    diagnostics.Add(new Diagnostic(
                        "SD.RHINO.PREVIEW_SOURCE_NOT_FOUND",
                        DiagnosticSeverity.Warning,
                        "The converted surface has no matching SimpleDragon source identifier.",
                        converted.Id,
                        suggestedAction: "Inspect conversion diagnostics and clone relationships."));
                }
                else
                {
                    double sourceOpeningArea = sourceSurface.Fenestrations.Sum(opening => opening.Area);
                    if (Math.Abs(sourceSurface.Area - converted.GrossArea) > tolerance)
                    {
                        diagnostics.Add(new Diagnostic(
                            "SD.RHINO.PREVIEW_SOURCE_GROSS_AREA_MISMATCH",
                            DiagnosticSeverity.Error,
                            "The converted InvisibleDragon gross area differs from its SimpleDragon source surface.",
                            converted.Id,
                            sourceGeometry,
                            "Inspect construction conversion and adjacency normalization."));
                    }

                    if (Math.Abs(sourceOpeningArea - convertedOpeningArea) > tolerance)
                    {
                        diagnostics.Add(new Diagnostic(
                            "SD.RHINO.PREVIEW_SOURCE_OPENING_AREA_MISMATCH",
                            DiagnosticSeverity.Error,
                            "The converted InvisibleDragon opening area differs from its SimpleDragon source surface.",
                            converted.Id,
                            sourceGeometry,
                            "Inspect fenestration conversion and cloned opening relationships."));
                    }

                    if (sourceGeometryMap is not null && sourceGeometry is null)
                    {
                        diagnostics.Add(new Diagnostic(
                            "SD.RHINO.PREVIEW_SOURCE_PROVENANCE_NOT_FOUND",
                            DiagnosticSeverity.Warning,
                            "The SimpleDragon source surface has no Rhino provenance entry.",
                            sourceSurface.Id,
                            suggestedAction: "Pass the complete RhinoZoneExtractionResult.GeometryMap to the preview builder."));
                    }
                }

                string fingerprint = RhinoGeometryFingerprint.ForFace(
                    converted.Polygon,
                    converted.Openings.Select(opening => opening.Polygon));
                Point3d labelPoint = FindTrimmedFaceLabelPoint(brep);
                exploded = brep.DuplicateBrep();
                Vector3d explodeVector = ExplodeVector(
                    converted,
                    convertedIndex,
                    context,
                    explodeDistanceMetres);
                Transform explodeTransform = Transform.Translation(explodeVector);
                if (!exploded.Transform(explodeTransform))
                {
                    throw new InvalidOperationException("The display-only exploded Brep could not be transformed.");
                }

                Point3d explodedLabelPoint = labelPoint;
                explodedLabelPoint.Transform(explodeTransform);
                var preview = new RhinoConvertedSurfacePreview(
                    converted.Id,
                    sourceSurface?.Id,
                    surfaceConversion?.SourceZoneId,
                    surfaceConversion?.ConvertedZoneId,
                    surfaceConversion?.IsSynthesizedCounterpart ?? false,
                    brep,
                    exploded,
                    labelPoint,
                    explodedLabelPoint,
                    sourceSurface?.Area,
                    sourceSurface?.Fenestrations.Sum(opening => opening.Area),
                    converted.GrossArea,
                    convertedOpeningArea,
                    converted.NetArea,
                    rhinoNetArea,
                    fingerprint,
                    sourceGeometry);
                previews.Add(preview);
                brep = null;
                exploded = null;
            }
            catch (Exception exception) when (
                exception is ArgumentException
                || exception is InvalidOperationException)
            {
                diagnostics.Add(new Diagnostic(
                    "SD.RHINO.PREVIEW_BREP_FAILED",
                    DiagnosticSeverity.Error,
                    "A converted surface could not be represented as a Rhino Brep: " + exception.Message,
                    converted.Id,
                    suggestedAction: "Inspect the converted polygon and opening topology."));
            }
            finally
            {
                brep?.Dispose();
                exploded?.Dispose();
            }

            convertedIndex++;
        }

        diagnostics.Add(new Diagnostic(
            "SD.RHINO.PREVIEW_USES_CONVERTED_GEOMETRY",
            DiagnosticSeverity.Info,
            "Preview Breps show the exact deterministic InvisibleDragon polygons generated from SimpleDragon areas; they are not copies of the original Rhino faces.",
            suggestedAction: "Use source and converted fingerprints together when comparing geometry loss."));
        return new RhinoConversionPreview(previews, diagnostics);
    }

    private static Point3d FindTrimmedFaceLabelPoint(Brep brep)
    {
        if (brep.Faces.Count == 0)
        {
            throw new InvalidOperationException("The converted preview Brep has no face for a label anchor.");
        }

        BrepFace face = brep.Faces[0];
        Interval domainU = face.Domain(0);
        Interval domainV = face.Domain(1);
        Point3d target = brep.GetBoundingBox(true).Center;
        Point3d? best = null;
        double bestDistance = double.PositiveInfinity;
        const int divisions = 40;
        for (int uIndex = 1; uIndex < divisions; uIndex++)
        {
            double u = domainU.ParameterAt(uIndex / (double)divisions);
            for (int vIndex = 1; vIndex < divisions; vIndex++)
            {
                double v = domainV.ParameterAt(vIndex / (double)divisions);
                if (face.IsPointOnFace(u, v) == PointFaceRelation.Exterior)
                {
                    continue;
                }

                Point3d candidate = face.PointAt(u, v);
                double distance = candidate.DistanceToSquared(target);
                if (distance < bestDistance)
                {
                    best = candidate;
                    bestDistance = distance;
                }
            }
        }

        return best ?? throw new InvalidOperationException(
            "No point on the trimmed converted face could be selected for its label.");
    }

    private static Vector3d ExplodeVector(
        DragonSurface converted,
        int convertedIndex,
        RhinoGeometryContext context,
        double explodeDistanceMetres)
    {
        if (explodeDistanceMetres == 0d)
        {
            return Vector3d.Zero;
        }

        GonieGonie.InvisibleDragon.Shape.Vector3 normal = converted.Polygon.Normal;
        double distance = context.FromMetres(explodeDistanceMetres * (1d + (convertedIndex * 0.05d)));
        return new Vector3d(normal.X * distance, normal.Y * distance, normal.Z * distance);
    }

    private static bool TryAdd<T>(Dictionary<string, T> dictionary, string key, T value)
    {
#if NET6_0_OR_GREATER
        return dictionary.TryAdd(key, value);
#else
        if (dictionary.ContainsKey(key))
        {
            return false;
        }

        dictionary.Add(key, value);
        return true;
#endif
    }

    private static T RequireNotNull<T>(T? value, string parameterName)
        where T : class
    {
#if NET7_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(value, parameterName);
#else
        if (value is null)
        {
            throw new ArgumentNullException(parameterName);
        }
#endif
        return value;
    }
}
